# Generated by Django 2.1.1 on 2018-09-21 18:37

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_Activity', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('description_time', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees_filter_one', models.IntegerField(choices=[(1, 'Horizontal filter one'), (2, 'Tags filter one')])),
                ('activity_filter_one', models.IntegerField(choices=[(1, 'Horizontal filter one'), (2, 'Tags filter one')])),
                ('employees_filter_two', models.IntegerField(choices=[(1, 'Horizontal filter two'), (2, 'Tags filter two')])),
                ('activity_filter_two', models.IntegerField(choices=[(1, 'Horizontal filter two'), (2, 'Tags filter  two')])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('can_change_password', models.BooleanField(blank=True, default=False)),
                ('identification', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Configuration One',
                'verbose_name_plural': 'Configurations Ones',
            },
        ),
        migrations.CreateModel(
            name='Activity2',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.Activity')),
            ],
            options={
                'verbose_name': 'Activity two',
                'verbose_name_plural': 'Activities two',
            },
            bases=('schedule.activity',),
        ),
        migrations.AddField(
            model_name='activity',
            name='employees',
            field=models.ManyToManyField(related_name='activities', to='schedule.Employee'),
        ),
        migrations.AddField(
            model_name='activity',
            name='trucks',
            field=models.ManyToManyField(related_name='activities', to='schedule.Truck'),
        ),
        migrations.AddField(
            model_name='activity',
            name='vista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Vista'),
        ),
    ]
