# Generated by Django 2.1.1 on 2018-10-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity2',
            options={'verbose_name': 'Activity two', 'verbose_name_plural': 'Activitys two'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='description_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='activity',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, related_name='activities', to='schedule.Employee'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(blank=True, help_text='The format is HH:MM'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='trucks',
            field=models.ManyToManyField(blank=True, null=True, related_name='activities', to='schedule.Truck'),
        ),
    ]
