# Generated by Django 2.1.1 on 2018-09-20 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('schedule', '0002_configuration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='type_filter',
            new_name='activity_filter',
        ),
        migrations.AddField(
            model_name='configuration',
            name='employees_filter',
            field=models.IntegerField(choices=[(1, 'Horizontal filter'), (2, 'Tags filter')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
    ]
