# Generated by Django 2.1.1 on 2018-10-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20181002_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(blank=True, help_text='The format is HH:MM', null=True),
        ),
    ]
