# Generated by Django 2.1.1 on 2018-09-20 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20180920_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vista',
            options={'verbose_name': 'Configuration One', 'verbose_name_plural': 'Configurations Ones'},
        ),
    ]
