# Generated by Django 2.1.1 on 2018-09-20 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20180920_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='start_date',
            new_name='date',
        ),
    ]
