# Generated by Django 2.1.1 on 2018-09-21 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20180920_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity2',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.Activity')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
            bases=('schedule.activity',),
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='activity_filter',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='employees_filter',
        ),
        migrations.AddField(
            model_name='configuration',
            name='activity_filter_one',
            field=models.IntegerField(choices=[(1, 'Horizontal filter one'), (2, 'Tags filter one')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='activity_filter_two',
            field=models.IntegerField(choices=[(1, 'Horizontal filter two'), (2, 'Tags filter  two')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='employees_filter_one',
            field=models.IntegerField(choices=[(1, 'Horizontal filter one'), (2, 'Tags filter one')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='employees_filter_two',
            field=models.IntegerField(choices=[(1, 'Horizontal filter two'), (2, 'Tags filter two')], default=1),
            preserve_default=False,
        ),
    ]
