# Generated by Django 2.1.1 on 2018-09-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20180921_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity2',
            options={'verbose_name': 'Activity two', 'verbose_name_plural': 'Activities two'},
        ),
    ]
