# Generated by Django 2.1.1 on 2018-09-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20180921_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_change_password',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
