# Generated by Django 2.1.1 on 2018-09-21 17:29

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('schedule', '0009_employee_can_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtraMethods',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
